### ISSUE TITLE
New Device: EcoFlow Powerstream

### ISSUE THREAD

**Issue by jguen** [PietroLubini/homebridge-ecoflow#17]
Hey, it would be a dream, to connect to the EcoFlow Powerstream.

**Comment by PietroLubini** [comment]
Hi,

1. What characteristics do you want to have possibility to control/view in HomeKit?
    - Input Consumption, W (read)
    - Output Consumption, W (read)
    - AC output power demand, W (read/write
    - etc
    It will be great if you make screenshot from your EcoFlow app and hightlight the metrics you want to have.
2. Will you participate in testing of a device? by 
    - setting up beta version of the plugin
    - following test cases i will provide
    - reporting back debug logs for each test case

**Comment by PietroLubini** [comment]
Hi @jguen,

I've added support for PowerStream Micro-inverter in [v1.3.0](https://github.com/PietroLubini/homebridge-ecoflow/releases/tag/v1.3.0-beta.3). Can you test it and provide feedback whether everything works fine?

<img src="https://github.com/user-attachments/assets/ad2e1156-4eb8-491b-ace4-a1660e009edf" alt="PowerStream" width="300">

<img src="https://github.com/user-attachments/assets/626c3801-e85d-44a7-8cfc-689dd89a2cf7" alt="PowerStream Characteristics" width="300">

**Comment by jguen** [comment]
Hey @PietroLubini, 

thank you for implementing the PowerStream so quick. 

I have downloaded the beta and the connection works fine. The only error is in the power values. They are factor 10 to high. (Real Value: 120W, shown value 1200W) 

> Hi @jguen,
> 
> I've added support for PowerStream Micro-inverter in [v1.3.0-beta.4](https://github.com/PietroLubini/homebridge-ecoflow/releases/tag/v1.3.0-beta.4). Can you test it and provide feedback whether everything works fine?
> 
> All supported characteristics are described [here ](https://github.com/PietroLubini/homebridge-ecoflow/blob/task/17-powerstream-support/README.md#powerstream-micro-inverter)
> 
> <img alt="PowerStream" width="300" src="https://private-user-images.githubusercontent.com/19411059/361191062-ad2e1156-4eb8-491b-ace4-a1660e009edf.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTYwNDQsIm5iZiI6MTcyNDY1NTc0NCwicGF0aCI6Ii8xOTQxMTA1OS8zNjExOTEwNjItYWQyZTExNTYtNGViOC00OTFiLWFjZTQtYTE2NjBlMDA5ZWRmLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQwNzAyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTRkZDlmMmM3ZTFmNTQ0MDRkYzQzZDFhODRhOTg4ZmYyZjg2NjczYWYxNjM2OWNmZDE3MzE0ZGQ4MGY3YzI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xOrZ7UYNGsREKyb0AJqDBOwWZ6psvIlOtQLfwg-HZ2E"> <img alt="PowerStream Characteristics" width="300" src="https://private-user-images.githubusercontent.com/19411059/361190998-626c3801-e85d-44a7-8cfc-689dd89a2cf7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTYwNDQsIm5iZiI6MTcyNDY1NTc0NCwicGF0aCI6Ii8xOTQxMTA1OS8zNjExOTA5OTgtNjI2YzM4MDEtZTg1ZC00NGE3LThjZmMtNjg5ZGQ4OWEyY2Y3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA3MDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNzU4NWQ3ZGNiMjM0ZjFlNzI0ZWNlZGVjOWY2Yzk0ZGY3NmE4MmQ4NzYwYzFkNjJlNDU0Yjg1MDFiM2I3MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f2gXWW3tHemGkLzk-QEQDcjUp0LBAtCVDDk9U-UIFbg">

**Comment by PietroLubini** [comment]
> Hey @PietroLubini,
> 
> thank you for implementing the PowerStream so quick.
> 
> I have downloaded the beta and the connection works fine. The only error is in the power values. They are factor 10 to high. (Real Value: 120W, shown value 1200W)
> 
> > Hi @jguen,
> > I've added support for PowerStream Micro-inverter in [v1.3.0-beta.4](https://github.com/PietroLubini/homebridge-ecoflow/releases/tag/v1.3.0-beta.4). Can you test it and provide feedback whether everything works fine?
> > All supported characteristics are described [here ](https://github.com/PietroLubini/homebridge-ecoflow/blob/task/17-powerstream-support/README.md#powerstream-micro-inverter)
> > <img alt="PowerStream" width="300" src="https://private-user-images.githubusercontent.com/19411059/361191062-ad2e1156-4eb8-491b-ace4-a1660e009edf.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTYwNDQsIm5iZiI6MTcyNDY1NTc0NCwicGF0aCI6Ii8xOTQxMTA1OS8zNjExOTEwNjItYWQyZTExNTYtNGViOC00OTFiLWFjZTQtYTE2NjBlMDA5ZWRmLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNlQwNzAyMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZTRkZDlmMmM3ZTFmNTQ0MDRkYzQzZDFhODRhOTg4ZmYyZjg2NjczYWYxNjM2OWNmZDE3MzE0ZGQ4MGY3YzI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xOrZ7UYNGsREKyb0AJqDBOwWZ6psvIlOtQLfwg-HZ2E"> <img alt="PowerStream Characteristics" width="300" src="https://private-user-images.githubusercontent.com/19411059/361190998-626c3801-e85d-44a7-8cfc-689dd89a2cf7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ2NTYwNDQsIm5iZiI6MTcyNDY1NTc0NCwicGF0aCI6Ii8xOTQxMTA1OS8zNjExOTA5OTgtNjI2YzM4MDEtZTg1ZC00NGE3LThjZmMtNjg5ZGQ4OWEyY2Y3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI2VDA3MDIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNzU4NWQ3ZGNiMjM0ZjFlNzI0ZWNlZGVjOWY2Yzk0ZGY3NmE4MmQ4NzYwYzFkNjJlNDU0Yjg1MDFiM2I3MDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f2gXWW3tHemGkLzk-QEQDcjUp0LBAtCVDDk9U-UIFbg">

Hi, 

Seems to be valid point. I've fixed it. Please, try [v1.3.0-beta.5](https://github.com/PietroLubini/homebridge-ecoflow/releases/tag/v1.3.0-beta.5)

**Comment by jguen** [comment]
Thank you for the fix :) The values are now shown correctly. For which value is the lightbulb brightness? Is it possible to connect it to the output power of the PowerStream-Converter. (0-100% <-> 0-800W)

**Comment by PietroLubini** [comment]
> Thank you for the fix :) The values are now shown correctly. For which value is the lightbulb brightness? Is it possible to connect it to the output power of the PowerStream-Converter. (0-100% <-> 0-800W)

_For which value is the lightbulb brightness?_
It is for "LIghting setting" in EcoFlow app
![image](https://github.com/user-attachments/assets/645cdf30-0ad1-41aa-b4cb-4b8f12016f04)

_Is it possible to connect it to the output power of the PowerStream-Converter?_
If you are talking about "AC output power demand", i've added Fan Rotation Speed (100% - 600/800) to control this setting. Note that if you have 800W PowerStream, you should set `powerstream`.`type` in config to 800. By the way, it is said in API documentation that max supported value for write operation is 600, so, please, try [v1.3.0-beta.6](https://github.com/PietroLubini/homebridge-ecoflow/releases/tag/v1.3.0-beta.6) and let me know whether 100% of fan rotation speed sets 800W in your EcoFlow app.

![image](https://github.com/user-attachments/assets/9117ffdd-e6fc-4d3c-882b-432115fd55de)
