### ISSUE TITLE
Installation Issues - hap-nodejs missing and wrong API URL (A vs E)

### ISSUE THREAD

**Issue by jamesbabiak** [PietroLubini/homebridge-ecoflow#8]
Thanks for the awesome plugin. After a bunch of troubleshooting, I was able to get it working, but ran into a couple of issues I wanted to bring to your attention.

**Describe The Bug:**
1) The plugin requires hap-nodejs, but after install it kept crashing because it wasn't able to find it. I confirmed I had hap-nodejs installed, but the plugin seemed to require it in its own node_modules directory. After running:
ln -s /usr/lib/node_modules/homebridge/node_modules/hap-nodejs hap-nodejs
to create a link to the actual hap-nodejs folder, that resolved the problem. 
I'm assuming this would cause issues for other people, as my HomeBridge setup is pretty simple/vanilla. My solution is more of a hack, so I wanted to let you know to see if it could be fixed in the code.

2) After fixing the hap-nodejs issue, I restarted HomeBridge and it loaded the plugin. Unfortunately, I was getting a ton of API issues which were so severe it actually started crashing HomeBridge. It would start up, load the plugin, get an API failure, load all the other plugins/devices, then crash. No explanation for the crash, but it only started doing this with the EcoFlow plugin enabled and stopped after I disabled it. I started reviewing the error messages and the API was getting an "invalid secret key" response from the server. I double checked my EcoFlow API key and confirmed it was correct. So I started reviewing the documentation and noticed a disparity. The documentation on EF's Dev website said to use api-a, but this plugin was using api-e. I'm going to assume that this may mean America vs Europe, and I'm in America and maybe you are in Europe. In any case, I searched for the API URL and found:
dist/apis/ecoFlowHttpApi.js:const ApiUrl = 'https://api-e.ecoflow.com';
I modified this to api-a, re-enabled the plugin, restarted HomeBridge, and voila, everything started working. Assuming that EcoFlow does have region based API servers which are not interchangeable, the URL it uses probably needs to be a configurable option in the settings. Also, it may need to have some catch so that if the API fails (e.g. wrong key, wrong server) it doesn't crash HomeBridge.

Fortunately, after fixing those two issues, it seems to be running properly and I can see my D2M in HomeKit.

**To Reproduce:**
Details above, but let me know if you need anything else.

**Expected behavior:**
It should use the existing hap-nodejs library directly or create its own symlink to it. And the API needs to be customizable. 

**Plugin Config:**
I only had 1 device configured (D2M), but that is irrelevant for the issues above as it never even got to the device part before running into both issues.

**Environment:**

* **Plugin Version**: Latest 1.2.0
* **Homebridge Version**: 1.8.4
* **Node.js Version**: 20.16.0
* **Operating System**: Ubuntu

**Comment by PietroLubini** [comment]
Hi
Thank for reporting the bug. Description and propositions are valid. The bugs will be fixed.

**Comment by jamesbabiak** [comment]
> Hi Thank for reporting the bugs. Description and propositions are valid. The bugs will be fixed.

Thank you! Regarding the API URL, I was just reading up on some of the documentation, commands, etc. and looking at other code examples to see what else I could do with it, outside of the HomeBridge integration, and I noticed many examples of people just using api.ecoflow.com. I edited my config again and changed it from api-a to just api, reloaded, and it's working fine with that as well. I'm wondering if that may dynamically point to the correct region IP. I did some tests and I think it does. For example, when looking up api.ecoflow.com in the US, it resolves to 35.71.180.141, which is the same as api-a. I did the same query from a server I have in France, and I got 52.223.173.135, which is the same as api-e. So changing the API URL to just use 'api' might be the easiest option.

**Comment by PietroLubini** [comment]
> > Hi Thank for reporting the bugs. Description and propositions are valid. The bugs will be fixed.
> 
> Thank you! Regarding the API URL, I was just reading up on some of the documentation, commands, etc. and looking at other code examples to see what else I could do with it, outside of the HomeBridge integration, and I noticed many examples of people just using api.ecoflow.com. I edited my config again and changed it from api-a to just api, reloaded, and it's working fine with that as well. I'm wondering if that may dynamically point to the correct region IP. I did some tests and I think it does. For example, when looking up api.ecoflow.com in the US, it resolves to 35.71.180.141, which is the same as api-a. I did the same query from a server I have in France, and I got 52.223.173.135, which is the same as api-e. So changing the API URL to just use 'api' might be the easiest option.

`api.ecoflow.com` is obsolete. It is not announced how long it will work, but i don't want to rely on it. So i will add one more property to configuration with possibility to choose API Host ("US" or "EU")

**Comment by PietroLubini** [comment]
Fixed in [v1.2.1](../releases/tag/v1.2.1)
